name: Deploy to Cloud Run
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      REPO: ${{ secrets.GAR_REPOSITORY }}
      IMAGE: ${{ secrets.IMAGE_NAME }}
      IMAGE_URI: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
      # Runtime configuration (from GitHub Environments/Variables)
      CLOB_HOST: ${{ vars.CLOB_HOST || 'https://clob.polymarket.com' }}
      POLYMARKET_PROXY_ADDRESS: ${{ vars.POLYMARKET_PROXY_ADDRESS }}
      SIGNATURE_TYPE: ${{ vars.SIGNATURE_TYPE || '1' }}
      CHAIN_ID: ${{ vars.CHAIN_ID || '137' }}
      EDGE_BPS: ${{ vars.EDGE_BPS || '50' }}
      MIN_LIQUIDITY_USD: ${{ vars.MIN_LIQUIDITY_USD || '1000' }}
      DEFAULT_SL_PCT: ${{ vars.DEFAULT_SL_PCT || '0.15' }}
      DEFAULT_TP_PCT: ${{ vars.DEFAULT_TP_PCT || '0.25' }}
      BOT_B_DEFAULT_CHAT_ID: ${{ vars.BOT_B_DEFAULT_CHAT_ID }}
      TELEGRAM_BOT_A_WEBHOOK_URL: ${{ vars.TELEGRAM_BOT_A_WEBHOOK_URL }}
      TELEGRAM_BOT_B_WEBHOOK_URL: ${{ vars.TELEGRAM_BOT_B_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CLOUD_RUN_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build and push image (lowercase repo/image)
        run: |
          REPO_LC="${REPO,,}"
          IMAGE_LC="${IMAGE,,}"
          IMAGE_URI_COMPUTED="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_LC/$IMAGE_LC:${GITHUB_SHA}"
          echo "IMAGE_URI_COMPUTED=$IMAGE_URI_COMPUTED" >> $GITHUB_ENV
          docker build -t "$IMAGE_URI_COMPUTED" .
          docker push "$IMAGE_URI_COMPUTED"

      - name: Deploy Bot A
        run: |
          gcloud run deploy polytrade-bot-a \
            --project $PROJECT_ID --region $REGION \
            --image "$IMAGE_URI_COMPUTED" \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.telegram.bot_a:app,GCP_PROJECT_ID=$PROJECT_ID,CLOB_HOST=$CLOB_HOST,POLYMARKET_PROXY_ADDRESS=$POLYMARKET_PROXY_ADDRESS,SIGNATURE_TYPE=$SIGNATURE_TYPE,CHAIN_ID=$CHAIN_ID,EDGE_BPS=$EDGE_BPS,MIN_LIQUIDITY_USD=$MIN_LIQUIDITY_USD,DEFAULT_SL_PCT=$DEFAULT_SL_PCT,DEFAULT_TP_PCT=$DEFAULT_TP_PCT,TELEGRAM_BOT_A_WEBHOOK_URL=$TELEGRAM_BOT_A_WEBHOOK_URL \
            --set-secrets WALLET_PRIVATE_KEY=WALLET_PRIVATE_KEY:latest,TELEGRAM_BOT_A_TOKEN=TELEGRAM_BOT_A_TOKEN:latest

      - name: Deploy Bot B
        run: |
          gcloud run deploy polytrade-bot-b \
            --project $PROJECT_ID --region $REGION \
            --image "$IMAGE_URI_COMPUTED" \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.telegram.bot_b:app,GCP_PROJECT_ID=$PROJECT_ID,CLOB_HOST=$CLOB_HOST,POLYMARKET_PROXY_ADDRESS=$POLYMARKET_PROXY_ADDRESS,SIGNATURE_TYPE=$SIGNATURE_TYPE,CHAIN_ID=$CHAIN_ID,EDGE_BPS=$EDGE_BPS,MIN_LIQUIDITY_USD=$MIN_LIQUIDITY_USD,DEFAULT_SL_PCT=$DEFAULT_SL_PCT,DEFAULT_TP_PCT=$DEFAULT_TP_PCT,BOT_B_DEFAULT_CHAT_ID=$BOT_B_DEFAULT_CHAT_ID,TELEGRAM_BOT_B_WEBHOOK_URL=$TELEGRAM_BOT_B_WEBHOOK_URL \
            --set-secrets WALLET_PRIVATE_KEY=WALLET_PRIVATE_KEY:latest,TELEGRAM_BOT_B_TOKEN=TELEGRAM_BOT_B_TOKEN:latest

      - name: Deploy Analyzer
        run: |
          gcloud run deploy polytrade-analyzer \
            --project $PROJECT_ID --region $REGION \
            --image "$IMAGE_URI_COMPUTED" \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.api.analyzer_app:app,GCP_PROJECT_ID=$PROJECT_ID,CLOB_HOST=$CLOB_HOST,POLYMARKET_PROXY_ADDRESS=$POLYMARKET_PROXY_ADDRESS,SIGNATURE_TYPE=$SIGNATURE_TYPE,CHAIN_ID=$CHAIN_ID,EDGE_BPS=$EDGE_BPS,MIN_LIQUIDITY_USD=$MIN_LIQUIDITY_USD,DEFAULT_SL_PCT=$DEFAULT_SL_PCT,DEFAULT_TP_PCT=$DEFAULT_TP_PCT \
            --set-secrets WALLET_PRIVATE_KEY=WALLET_PRIVATE_KEY:latest

      - name: Deploy Monitor
        run: |
          gcloud run deploy polytrade-monitor \
            --project $PROJECT_ID --region $REGION \
            --image "$IMAGE_URI_COMPUTED" \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.api.monitor_app:app,GCP_PROJECT_ID=$PROJECT_ID,CLOB_HOST=$CLOB_HOST,POLYMARKET_PROXY_ADDRESS=$POLYMARKET_PROXY_ADDRESS,SIGNATURE_TYPE=$SIGNATURE_TYPE,CHAIN_ID=$CHAIN_ID,EDGE_BPS=$EDGE_BPS,MIN_LIQUIDITY_USD=$MIN_LIQUIDITY_USD,DEFAULT_SL_PCT=$DEFAULT_SL_PCT,DEFAULT_TP_PCT=$DEFAULT_TP_PCT \
            --set-secrets WALLET_PRIVATE_KEY=WALLET_PRIVATE_KEY:latest


