name: Deploy to Cloud Run
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      REPO: ${{ secrets.GAR_REPOSITORY }}
      IMAGE: ${{ secrets.IMAGE_NAME }}
      IMAGE_URI: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CLOUD_RUN_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build and push image
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy Bot A
        run: |
          gcloud run deploy polytrade-bot-a \
            --project $PROJECT_ID --region $REGION \
            --image $IMAGE_URI \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.telegram.bot_a:app

      - name: Deploy Bot B
        run: |
          gcloud run deploy polytrade-bot-b \
            --project $PROJECT_ID --region $REGION \
            --image $IMAGE_URI \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.telegram.bot_b:app

      - name: Deploy Analyzer
        run: |
          gcloud run deploy polytrade-analyzer \
            --project $PROJECT_ID --region $REGION \
            --image $IMAGE_URI \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.api.analyzer_app:app

      - name: Deploy Monitor
        run: |
          gcloud run deploy polytrade-monitor \
            --project $PROJECT_ID --region $REGION \
            --image $IMAGE_URI \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars APP_MODULE=polytrade.api.monitor_app:app


